//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor : Korisnik
    {
        private string korisnickoIme;

        public Doktor()
        {
            this.Pregleds = new HashSet<Pregled>();
            this.Pregled_Specijaliste = new HashSet<Pregled_Specijaliste>();
            this.Dodatni_Pregled = new HashSet<Pregled_Specijaliste>();
        }

        public Doktor(string ime, string prezime, string korisnickoIme, string lozinka, string uloga, string kontakt, string email, string ulica, string grad, string broj, string specijalizacija)
        {
            Ime = ime;
            Prezime = prezime;
            this.Korisnicko_Ime = korisnickoIme;
            Lozinka = lozinka;
            Uloga = uloga;
            Kontakt = kontakt;
            Email = email;
            Ulica = ulica;
            Grad = grad;
            Broj = broj;
            Specijalizacija = specijalizacija;
        }

        public string Specijalizacija { get; set; }
    
        public virtual Departman Departmen { get; set; }
        public virtual ICollection<Pregled> Pregleds { get; set; }
        public virtual ICollection<Pregled_Specijaliste> Pregled_Specijaliste { get; set; }
        public virtual ICollection<Pregled_Specijaliste> Dodatni_Pregled { get; set; }
    }
}
