//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terapija
    {
        public Terapija()
        {

        }
        public Terapija(string naziv, string opis, string vrsta_Terapije)
        {
            Naziv = naziv;
            Opis = opis;
            Vrsta_Terapije = vrsta_Terapije;
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Vrsta_Terapije { get; set; }
    
        public virtual Dijagnoza Dijagnoza { get; set; }
    }
}
